# This is the
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: check-json
        -   id: pretty-format-json

  -   repo: https://github.com/FelixSeptem/pre-commit-golang
      rev: 12f5442f51377b10b26651ad745206bbe1500ad6
      hooks:
        -   id: bazel-buildifier
        -   id: go-imports
        -   id: golangci-lint
